CREATE TABLE IF NOT EXISTS Outreach (
  OutreachID SERIAL PRIMARY KEY,
  FacultyID  INT NOT NULL,
  Description TEXT NOT NULL,
  DateConducted DATE NOT NULL,
  Location   VARCHAR(255),

  FOREIGN KEY (FacultyID) REFERENCES Faculty(FacultyID) ON DELETE CASCADE
);
 
